# This config file is used by ros2_control
controller_manager:
  ros__parameters:
    update_rate: 100  # Hz

    arm_controller:
      type: joint_trajectory_controller/JointTrajectoryController

    prbt_joint_1_controller:
      type: canopen_ros2_controllers/Cia402DeviceController
    
    prbt_joint_2_controller:
      type: canopen_ros2_controllers/Cia402DeviceController
    
    prbt_joint_3_controller:
      type: canopen_ros2_controllers/Cia402DeviceController

    prbt_joint_4_controller:
      type: canopen_ros2_controllers/Cia402DeviceController

    prbt_joint_5_controller:
      type: canopen_ros2_controllers/Cia402DeviceController

    prbt_joint_6_controller:
      type: canopen_ros2_controllers/Cia402DeviceController

    joint_state_broadcaster:
      type: joint_state_broadcaster/JointStateBroadcaster


prbt_joint_1_controller:
  ros__parameters:
    joint: prbt_joint_1

prbt_joint_2_controller:
  ros__parameters:
    joint: prbt_joint_2

prbt_joint_3_controller:
  ros__parameters:
    joint: prbt_joint_3

prbt_joint_4_controller:
  ros__parameters:
    joint: prbt_joint_4

prbt_joint_5_controller:
  ros__parameters:
    joint: prbt_joint_5

prbt_joint_6_controller:
  ros__parameters:
    joint: prbt_joint_6


arm_controller:
  ros__parameters:
    joints:
      - prbt_joint_1
      - prbt_joint_2
      - prbt_joint_3
      - prbt_joint_4
      - prbt_joint_5
      - prbt_joint_6
    command_interfaces:
      - position
    state_interfaces:
      - position
      - velocity